import { MessageCircleQuestion, Waypoints } from 'lucide-react'
import { pick } from './links'
import { AIGW_CATALOG } from './aigw-catalog'

/**
 * The whole AI Gateway doc set as one guide: every page from the official
 * llms.txt indexes (aigw-catalog.js, generated by scripts/gen-aigw-catalog.mjs),
 * grouped by area with a one-line description each. Its data is part of the
 * guide's blocks, so the rail search finds any page title too.
 */
export const CATALOG = [
  {
    id: 'docs-aigw',
    group: 'library',
    title: 'Every AI Gateway doc page',
    sub: `All ${AIGW_CATALOG.pages} pages of the official docs, grouped, described and filterable`,
    minutes: 2,
    level: 'Reference',
    docs: pick('agGateway', 'agWelcome'),
    blocks: [
      {
        type: 'prose',
        text: [
          `The Prisma AIRS AI Gateway developer docs at portkey.ai/docs/aigw run to ${AIGW_CATALOG.pages} pages: the product, model providers and partner integrations, self-hosting, the inference and admin API references, the changelog and the help center. Every one is listed below with one line on what it is for.`,
          'The guides in this corner distil the pages that matter for a Prisma AIRS deployment and say where the docs contradict themselves or this portal\'s tenant. For anything else, filter this list — or ask the docs a question and get an answer that cites these pages.',
        ],
      },
      {
        type: 'cards',
        min: 260,
        items: [
          { icon: MessageCircleQuestion, tone: '#EC4899', title: 'Ask instead of browsing', kicker: 'Ask the AI Gateway docs',
            text: 'Type a question; the answer comes from these pages only, and every claim links to its page.', go: 'ask', goLabel: 'Ask the docs' },
          { icon: Waypoints, tone: '#EC4899', title: 'Start with the essentials', kicker: 'SCM AI Gateway',
            text: 'What the gateway is, the objects you create, and how to send the first request.', go: 'gw-overview' },
        ],
      },
      { type: 'catalog', catalog: AIGW_CATALOG },
    ],
  },
]
