import { Terminal, ScanSearch, Swords, Fingerprint, Waypoints, Activity } from 'lucide-react'
import { pick } from './links'

/**
 * Library — every official document in one place, a cross-product
 * troubleshooting table, and a map of where each integration runs in this
 * portal.
 */

export const LIBRARY = [
  {
    id: 'docs-all',
    group: 'library',
    title: 'All official documentation',
    sub: 'Guides, API references, SDKs and repositories',
    minutes: 2,
    level: 'Reference',
    docs: pick('docsHub', 'pandev'),
    blocks: [
      {
        type: 'prose',
        text: 'Every link below was opened and returned a page — on 2026-09-28, and the AI Gateway developer docs on 2026-10-01. Admin guides live on docs.paloaltonetworks.com (the PDFs are the complete, printable versions); API references live on pan.dev; the AI Gateway\'s developer docs are at portkey.ai/docs/aigw (docs.gw.prismaairs.com serves the same pages). For anything the guides do not cover, ask the docs (top of the rail) or open the full catalog of AI Gateway pages.',
      },
      { type: 'links', title: 'Admin guides (PDF)', items: pick('pdfRuntime', 'pdfSupply', 'pdfRedTeam', 'pdfAgentId') },
      { type: 'links', title: 'AI Runtime API', items: pick('rtOverview', 'rtSync', 'rtAsync', 'rtResults', 'rtReports', 'rtErrors', 'rtUseCases', 'scanSpec', 'rbac', 'scanOauth') },
      { type: 'links', title: 'Python SDKs and packages', items: pick('sdkOverview', 'sdkUsage', 'sdkAsyncio', 'pypiSdk', 'ghSdk', 'mgmtApi', 'mgmtSdk', 'pypiMgmt', 'ghMgmt', 'pypiRelay', 'ghRelay') },
      { type: 'links', title: 'AI Gateway — admin guide', items: pick('gwOverview', 'gwDeploy', 'gwConfigs', 'gwKeys', 'gwGuardrails', 'gwAirsGuard', 'gwSpec', 'ghGwDocker') },
      { type: 'links', title: 'AI Gateway developer docs — the API and routing', items: pick('agWelcome', 'gwDevSetup', 'agFeatures', 'agApiRef', 'agHeaders', 'agAuth', 'agUniversal', 'agMessages', 'agResponses', 'agDecisions', 'agStrict', 'agCustomHosts', 'agConfigs', 'agFallbacks', 'agRetries', 'agLoadBalance', 'agConditional', 'agCircuit', 'agCache', 'agTimeouts') },
      { type: 'links', title: 'AI Gateway developer docs — guardrails and observability', items: pick('agGuardrails', 'gwDevGuard', 'agGuardCaps', 'agGuardList', 'agPii', 'agByo', 'agOrgGuard', 'agLogs', 'agTraces', 'agMetadata', 'agFeedback', 'agLogsExport', 'agOtel', 'agOtelExport') },
      { type: 'links', title: 'AI Gateway developer docs — MCP, agents and coding agents', items: pick('agMcp', 'agMcpQuick', 'gwDevMcp', 'agMcpRegistry', 'agMcpAuth', 'agMcpCas', 'agMcpGuard', 'agMcpRegApi', 'agAgentGw', 'agAgentQuick', 'agCoding', 'agClaudeCode', 'agCodex', 'agCursor', 'agOpenaiAgents', 'agLanggraph') },
      { type: 'links', title: 'AI Gateway developer docs — governance and admin', items: pick('agKeys', 'agKeyRotation', 'gwDevJwt', 'agBudget', 'agRate', 'agPolicies', 'agDefaultCfg', 'agSavedOnly', 'agCatalog', 'agSecretRefs', 'agRoles', 'agSso', 'agScim', 'agCie', 'agAudit', 'agKms') },
      { type: 'links', title: 'AI Model Security', items: pick('msInstall', 'msScanning', 'msApi', 'msSdk', 'msListScans', 'msErrors', 'scmTokens') },
      { type: 'links', title: 'AI Red Teaming', items: pick('rtmIntro', 'rtmOverview', 'rtmCreateTgt', 'rtmCreateScan', 'rtmChannels', 'rtmErrors', 'ghRtClient') },
      { type: 'links', title: 'Integrations and samples', items: pick('ghIntegrations', 'litellm', 'kong', 'ghN8n', 'ghNemo', 'ghRag') },
      {
        type: 'callout', tone: 'warn', title: 'Links that no longer work',
        text: 'The SDK README and its PyPI page still point at `pan.dev/prisma-airs/scan/api/` and `pan.dev/ai-runtime-security/scan/api/`; both return 404. So do `pan.dev/prisma-airs/` (use `pan.dev/airs/`) and `…/airuntimesecurity/scan-sync-request/` without `/scan/`. If a customer sends you one of these, the working pages are above.',
      },
      {
        type: 'table',
        title: 'Where the official sources disagree',
        columns: ['Topic', 'Source A', 'Source B', 'What to tell a customer'],
        minWidth: 640,
        rows: [
          ['Async batch size', 'pan.dev API: up to 25 requests', 'Python SDK: 5 scan objects', 'Plan for 5 with the SDK; 25 over raw REST'],
          ['Python floor for `pan-aisecurity`', 'pan.dev: 3.9', 'PyPI metadata (0.11.0): 3.10', 'Use 3.10 or later'],
          ['AI Gateway auth', 'PANW docs: `x-portkey-api-key` + virtual key', 'Developer docs: `Authorization: Bearer` + `@slug/model`', 'Both authenticate on the SCM gateway (tested); prefer Bearer + `@slug/model`'],
          ['Gateway guardrail JSON', '`before_request_hooks` / `after_request_hooks`', '`input_guardrails` / `output_guardrails`', 'Either shape; configs are usually built in the console anyway'],
          ['OAuth token URL', '`/oauth2/access_token` (SCM, Model Security)', '`/am/oauth2/access_token` (management SDK default)', 'The first one is used everywhere in this portal'],
          ['Gateway metering', 'Admin guide: 1 token = 4 characters for everything', 'Onboarding guide: LLM prompts use the model\'s own token counts', 'The onboarding guide is newer'],
          ['Guardrail block status', 'Developer docs: 446 when denied, 246 when let through', 'This portal\'s SCM tenant: HTTP 200, content replaced, verdict `false`', 'Read the `hook_results` verdicts and handle all three'],
          ['PII and moderation', 'Admin guide: handled by Prisma AIRS, not by gateway guardrails', 'Developer docs: PRO checks for PII (with redaction) and moderation', 'Check Guardrails → Create on the tenant'],
          ['`/v1/messages` on non-Claude models', 'Universal API and Messages pages: any provider', 'Bedrock and Vertex AI pages: Claude only', 'Test the model before relying on it'],
          ['Weekly budget reset', 'Budget pages: Sunday 00:00 UTC', 'Policies page: Monday 00:00 UTC', 'Watch the first reset on the tenant'],
          ['Gateway Admin API', 'Admin API reference: an SCM service-account token on `api.apps.paloaltonetworks.com/ai_gw/v2` or `/ai_gw/admin/v2`; a gateway key gets 401', 'Policies, feedback, pricing and MCP-guardrail product pages still show a gateway key on `aigw.portkey.ai/v1`', 'Follow the reference — see "Admin API: the gateway as code"'],
        ],
      },
    ],
  },

  {
    id: 'troubleshooting',
    group: 'library',
    title: 'Troubleshooting',
    sub: 'The errors customers actually hit, and what fixes them',
    minutes: 7,
    level: 'Reference',
    docs: pick('rtErrors', 'msErrors', 'rtmErrors', 'gwKeys', 'arErrors', 'arAdminErrors', 'agAb03', 'agMcpTrouble'),
    blocks: [
      {
        type: 'prose',
        text: 'Collected from the official error references and from building this portal. The ones marked with the portal were learned the hard way — the docs do not mention them.',
      },
      {
        type: 'table',
        title: 'AI Runtime API',
        columns: ['Symptom', 'Cause', 'Fix'],
        rows: [
          ['401', 'No `x-pan-token` (or Bearer token) sent', 'Check the header name and that the variable is exported in the process that makes the call'],
          ['403', 'Key invalid, revoked or expired', 'Regenerate it in SCM → API Applications; keys rotate on the schedule you chose'],
          ['400 "AI Profile not found"', 'The profile name does not exist **in the tenant the key belongs to**', 'A key and a profile from two different tenants look exactly like a typo. Check both come from the same TSG'],
          ['400 "No default AI profile available"', 'No `ai_profile` in the body and no default profile on the key', 'Always send `ai_profile.profile_name`'],
          ['413', 'Over 2 MB (sync) or 5 MB (async)', 'Chunk the content, or use async'],
          ['415', 'Missing or wrong `Content-Type`', '`Content-Type: application/json`'],
          ['429 "Requests per second exceeded"', 'Bursts from one key (no `retry_after`)', 'Retry after a short backoff (250–600 ms)'],
          ['429 on `/v1/scan/reports` or `/results`', 'The 10-per-minute limit on results and reports', 'Do not retry in a loop; fetch reports only when you need them, off the request path'],
          ['DLP silently not firing under load (portal)', 'Faster than about one scan per 2 s, DLP was observed returning false with no error flag', 'Space out bulk or test scans; do not conclude "not detected" from a burst'],
          ['`CERTIFICATE_VERIFY_FAILED` (portal)', 'Corporate TLS inspection', 'Point `SSL_CERT_FILE` / `NODE_EXTRA_CA_CERTS` at a bundle with the inspection CA'],
          ['Tool event scan 400 "cannot unmarshal object" (portal)', 'A `tools/list` output wrapped as `{"tools": […]}`', 'Send the bare array of tools'],
          ['Tool event blocked but no reason shown (portal)', 'Reading only `prompt_detected`', 'Tool detections are under `tool_detected.input_detected` / `output_detected`'],
        ],
      },
      {
        type: 'table',
        title: 'AI Gateway',
        columns: ['Symptom', 'Cause', 'Fix'],
        rows: [
          ['Every attack "passes" (portal)', 'A guardrail block is HTTP 200 with the content replaced; code only catches exceptions', 'Read `hook_results.*_hooks[].verdict === false`'],
          ['HTTP 200, content replaced by "The guardrail checks defined in the config failed…"', 'A soft deny: the `soft_deny_200` flag (gateway 2.14.0) answers a denial with 200 instead of 446, for clients that treat 4xx as fatal such as Claude Code. This portal\'s tenant answers this way', 'Treat it as a block; read the verdicts in `hook_results` (needs strict compliance off)'],
          ['`hook_results` missing on allowed responses', 'Strict OpenAI compliance strips non-OpenAI fields', 'Send `x-portkey-strict-open-ai-compliance: false`'],
          ['401 with the Portkey SDK (portal)', 'The SDK defaults to `api.portkey.ai`', 'Pass `baseURL: "https://aigw.portkey.ai/v1"`'],
          ['401 "Invalid API Key. Error Code: 03"', 'Missing or bad key. From this portal: every JWT failure looks the same — bad signature, expired token, unknown `kid`, `alg: none` (the docs quote the string only on the MCP troubleshooting page)', 'Decode the token and check `exp`, `kid` and the JWKS. A valid JWT whose scope or workspace is not allowed gets 403 instead (JWT page)'],
          ['`model_not_allowed` (portal)', 'Seen through the SCM gateway for models the integration does not provision; the docs name no error code for this', 'Enable the model under the integration\'s model provisioning. Since 2.27.0 a Bedrock allow-list also admits the `us.*` profile of an allowed base model'],
          ['"Model X is not allowed for this integration" for a model that is provisioned (portal)', 'A `targets`/`strategy` provider pin in the config overrides the `@slug/`', 'Remove the pin — and remove `strategy` together with `targets`'],
          ['400 on a request that sends `x-portkey-config`', 'The key\'s default config has **Allow Config Override** off', 'Drop the header, or allow override on the key'],
          ['Inline JSON config rejected', 'Inline configs are blocked on the tenant', 'Save the config and send its `pc-…` id'],
          ['412 / 429', 'Budget or rate limit reached (on the key, the JWT, the integration or a policy) — a 429 can also come from the provider', 'Wait for the reset. Integration-level limits cannot be edited; key limits can, and policies take a `PUT`'],
          ['400 `inline_config_blocked`, `inline_provider_blocked`, `inline_custom_host_blocked`…', 'Block Inline Configs is on — the default for organisations created on or after 19 June 2026', 'Send a saved `pc-…` config and `@slug` providers; set custom hosts and forward headers on the saved provider'],
          ['HTTP 246 or 446', 'A synchronous guardrail failed — 246 let the request through, 446 denied it', 'Read `hook_results`. To try another model, list `246` / `446` in a fallback\'s `on_status_codes` — 246 is a 2xx, so the default fallback ignores it'],
          ['408', 'A timeout — the config\'s `request_timeout`, or the provider\'s own (the Errors page lists both)', 'Add `408` to retry or fallback `on_status_codes` — it is not in the default retry list'],
          ['"Either x-portkey-config or x-portkey-provider header is required" (portal)', 'Smart quotes pasted into the curl `-d` JSON broke the body, so no model was parsed', 'Retype the quotes as straight ASCII'],
          ['"The security token included in the request is invalid" on a Bedrock integration (portal)', 'Assumed Role auth on the SCM gateway — no `sts:AssumeRole` ever reached the account — or a stale key cached after editing the integration\'s credentials', 'Use an access-key integration; after changing credentials, delete and recreate the integration'],
          ['Claude Code: `API Error: 500 fetch failed`', '`CLAUDE_CODE_USE_BEDROCK` / `CLAUDE_CODE_USE_VERTEX` with a provider base URL, or `/v1` on `ANTHROPIC_BASE_URL`', '`ANTHROPIC_BASE_URL=https://aigw.portkey.ai` and `x-portkey-provider` in `ANTHROPIC_CUSTOM_HEADERS`'],
          ['Claude Code: 403 `AccessDeniedException` on a non-Claude Bedrock model', 'Prompt-caching and beta headers sent to a model that does not take them', '`DISABLE_PROMPT_CACHING=1` and `CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS=1`'],
          ['Streamed requests log 0 tokens and 0 cost', 'Usage was not requested', 'Send `stream_options: { "include_usage": true }`'],
        ],
      },
      {
        type: 'table',
        title: 'MCP Gateway',
        columns: ['Symptom', 'Cause', 'Fix'],
        rows: [
          ['JSON-RPC error `-32446`', 'An MCP guardrail blocked the tool call', 'Check the guardrails mapped to that server or tool'],
          ['500 "Unable to verify user access"', 'The key type: a Service key on a server that uses per-user OAuth 2.1, or a key without `mcp.invoke`', 'Use a User key (or an OAuth / IdP sign-in) for per-user OAuth servers; give the key `mcp.invoke`'],
          ['403 / 404', 'Wrong slug (the registry slug, not a UUID), server not provisioned to the workspace, or a key from another workspace', 'Copy the URL from the console — this portal\'s tenant serves MCP from a different host than the docs show'],
          ['"Incompatible auth server: does not support dynamic client registration"', 'The upstream (e.g. Snowflake, or a server behind Okta or Entra) refuses dynamic client registration', 'Register an OAuth client there and add `client_id` / `client_secret` under `oauth_metadata` — with that wrapper only in the Advanced Configuration box, never in the OAuth Metadata field, or the gateway silently falls back to registration'],
          ['`external_auth_config` returns 403', 'Brokering your own IdP is hybrid-only; it is blocked on managed SaaS', 'On SaaS use `oauth_metadata` with a pre-registered client'],
          ['502 naming the server', 'The external MCP server cannot be reached (DNS failure, refused connection) — gateway 2.27.0 and later; earlier versions return a plain 500', 'Check the server URL and that it is reachable from the gateway'],
        ],
      },
      {
        type: 'table',
        title: 'AI Gateway Admin API',
        columns: ['Symptom', 'Cause', 'Fix'],
        rows: [
          ['401 `AB05` on any Admin endpoint', 'A gateway API key sent instead of an SCM access token — or the token expired (15 minutes) or was truncated', 'Mint a token from an SCM service account (`POST https://auth.apps.paloaltonetworks.com/oauth2/access_token`, `scope=tsg_id:<tsg-id>`) and refresh it before it lapses'],
          ['403 `AB03`', 'The token belongs to another tenant, the service account\'s role does not cover the call, or `workspace_id` points elsewhere', 'Check the token\'s `tsg_id`, the role and the workspace'],
          ['400 `AB01`', 'The body failed validation: a missing field, a wrong type, a value outside an enum', 'Compare it with the endpoint\'s reference page'],
          ['404 `AB08` (or `AB02`)', 'A slug where an id is expected or the reverse, or a resource in a workspace you did not name', 'Configs, integrations and providers take slugs; guardrails, MCP servers, policies and keys take ids. `workspace_id` in the query on GET, in the body on POST and PUT'],
          ['409 `AB07`', 'The resource already exists — creates are not idempotent', 'Check before retrying a create that timed out'],
          ['429 `AB06` · 500 `AB04` · 402 `AB09`', 'Rate limited · server error · subscription exhausted', 'Back off and retry · retry later · check the subscription'],
          ['A policy, secret-reference or guardrail call copied from a product page fails', 'Those pages still show `aigw.portkey.ai/v1/…` with a gateway key', 'Use the API reference: SCM token on `api.apps.paloaltonetworks.com/ai_gw/v2` (policies, workspace guardrails) or `/ai_gw/admin/v2` (secret references, organisation guardrails)'],
        ],
      },
      {
        type: 'table',
        title: 'Model Security and Red Teaming',
        columns: ['Symptom', 'Cause', 'Fix'],
        rows: [
          ['`pip install` cannot find `model-security-client` (or installs 0.0.1)', 'Not using the private index — or picking up the public placeholder', 'Install with `--extra-index-url "$(./get_pypi_url.sh)"` and pin `==1.1.2`'],
          ['400 "Both start_time and end_time must be specified" (portal)', 'The documented `list_scans(start_time=…)` sample', 'Pass `end_time` too'],
          ['400 on a scan', 'The security group\'s source type does not match the model (e.g. an S3 group for a Hugging Face URI)', 'Use a group for that source'],
          ['403', 'Missing role permission (`ai_ms_pypi_auth`, `ai_ms.scans`, `ai_ms.security_groups`) or an expired deployment profile', 'Fix the service account\'s role; check the profile association'],
          ['"N files pending scan data retrieval" (portal)', 'First scan of a repository — AIRS is still fetching it', 'Retry after a minute'],
          ['Local scan: "Model scan failed with no result" (portal)', 'The SDK spawns a child process for local scans; a server started at import time re-runs in the child', 'Start your server under `if __name__ == "__main__":`'],
          ['Red Teaming 400 `QUOTA_EXCEEDED`', 'Monthly scans for that job type used up', 'Raise the deployment profile allocation or wait for the month'],
          ['Red Teaming 403', 'Permissions, licence, or the EULA not accepted', 'Accept the EULA once in the console'],
        ],
      },
    ],
  },

  {
    id: 'this-portal',
    group: 'library',
    title: 'See each integration in this portal',
    sub: 'Which pillar demonstrates which path — and the file behind it',
    minutes: 3,
    level: 'Reference',
    docs: pick('pandev'),
    blocks: [
      {
        type: 'prose',
        text: 'This portal is a working reference implementation. Credentials stay on the server; every browser request goes through an Express proxy that calls Prisma AIRS exactly as the guides describe.',
      },
      {
        type: 'cards',
        items: [
          { icon: Terminal, tone: '#f43f5e', title: 'AIRS Runtime & AI-GW', kicker: 'Runtime API · AI Gateway · MCP',
            text: 'The same attack through two architectures: scans around the model call in the app (Vertex, Bedrock, Azure), or the guardrail inside the SCM AI Gateway, with MCP tool calls scanned in two stages.',
            bullets: ['`server.js` — `airscan()`, `/api/chat`', '`telemetry.js` — `airsFetch()`, 429 handling', '`mcp-aigw.js` — tool-event scans'],
            go: 'pillar:apiIntercept', goLabel: 'Open the console' },
          { icon: ScanSearch, tone: '#6366f1', title: 'AI Supply Chain', kicker: 'Model Security SDK · AIMS API',
            text: 'Real Hugging Face and local scans, and the tenant\'s scan history.',
            bullets: ['`scanner_app.py` — `client.scan()`', '`server.js` — `/api/supply-chain/*`', '`setup-scanner.sh` — private index install'],
            go: 'pillar:modelScanning', goLabel: 'Open AI Supply Chain' },
          { icon: Swords, tone: '#fb923c', title: 'Red Teaming', kicker: 'Red Teaming API',
            text: 'Targets, campaigns, reports and the recommended runtime profile.',
            bullets: ['`server.js` — `rtFetch()`, `/api/redteam/*`'],
            go: 'pillar:redTeaming', goLabel: 'Open Red Teaming' },
          { icon: Fingerprint, tone: '#8b5cf6', title: 'Enterprise AI Access', kicker: 'AI Gateway · JWT',
            text: 'Entra ID sign-in, an RS256 credential minted per user, and routing by role in a conditional config.',
            bullets: ['`access-routes.js` — `mintCredential()`'],
            go: 'pillar:enterpriseAccess', goLabel: 'Open Enterprise AI Access' },
          { icon: Waypoints, tone: '#0ea5e9', title: 'Ministry of Health', kicker: 'AI Gateway · tool events · uploads',
            text: 'A bilingual citizen app: gateway guardrails for model turns, direct tool-event scans for agent tools, and scanned file uploads.',
            bullets: ['`moh-routes.js` — `buildAigwClient()`', '`file-extract.js` — upload extraction'],
            go: 'pillar:ministryHealth', goLabel: 'Open the pillar' },
          { icon: Activity, tone: '#22c55e', title: 'LLM Telemetry', kicker: 'Traces',
            text: 'Every request from every pillar, with the measured timeline, the AIRS scan and report, and gateway hooks.',
            bullets: ['`traceStore.js` — trace storage'],
            go: 'pillar:observability', goLabel: 'Open telemetry' },
        ],
      },
      {
        type: 'table',
        title: 'Environment variables, by product',
        columns: ['Product', 'Variables (official SDK / this portal)'],
        rows: [
          ['Runtime API — Python SDK', '`PANW_AI_SEC_API_KEY` (or `PANW_AI_SEC_API_TOKEN`), `PANW_AI_SEC_API_ENDPOINT`; the profile name is yours to pass'],
          ['Runtime API — this portal', '`AIRS_API_KEY`, `AIRS_PROFILE_NAME`, `AIRS_BASE_URL`'],
          ['AI Gateway — this portal', '`AIGW_BASE_URL`, `AIGW_API_KEY`, `AIGW_CONFIG_PROTECTED`, `AIGW_CONFIG_UNPROTECTED`'],
          ['Model Security', '`MODEL_SECURITY_CLIENT_ID`, `MODEL_SECURITY_CLIENT_SECRET`, `TSG_ID`, `MODEL_SECURITY_API_ENDPOINT`'],
          ['Red Teaming — this portal', 'The same service-account variables as Model Security'],
          ['Hosted MCP server / relay', 'Server: `x-pan-token` + `x-pan-profile` headers. Relay: `apiKey` / `aiProfile` in its YAML (the example substitutes `${PRISMA_AIRS_API_KEY}`)'],
        ],
        note: 'Never commit these. The portal keeps them in a git-ignored `.env` per host.',
      },
    ],
  },
]
